### ISSUE TITLE
Preloading improvements

### ISSUE THREAD

**Issue by R3voA3** [Asaayu/3Den-Stringtable-Viewer#11]
- Preloading should be started when opening the GUI and should not be stopped by closing it. That way players can do other things while it's preloading and come back to the GUI when it's done. 

When preloading has finished, an Eden notification could pop up if the GUI is not open, to inform the player.

**Comment by ConnorAU** [comment]
Technically it does already work like this, I think it just overwrites the active preload results if you start preloading again before the first attempt completes. 

Building on this idea, I think it should actually start preloading when the eden editor display opens, that way it may already be preloaded by the time you open the mod display for the first time.

This would only require a few alterations:
- Start preloading when the editor display is created
- The preload function should not run if it is already running
- The preload function should only print the % loaded if the text ctrl exists
- R3vo’s 3den notification suggestion

**Comment by R3voA3** [comment]
Yeah, I already thought about starting it when Eden Starts. 

* We could start the preload by executing the preload function by an onTerrainNew Eden EH
* Add an optional setting in preferences to disable immediate preload when Eden is started.

**Comment by Asaayu** [comment]
Sorry about the wait fellas.
Thanks for the help, I've updated the steam workshop to the latest GitHub version which includes the changes in the pull request.
:)
