### ISSUE TITLE
Missing localisation string

### ISSUE THREAD

**Issue by R3voA3** [Asaayu/3Den-Stringtable-Viewer#16]
16:44:43 String STR_STRINGTABLE_BUTTON_CUSTOM_PATHS not found

**Comment by Asaayu** [comment]
Looks like your addition of German translations removed the string from the string table.
https://github.com/Asaayu/3Den-Stringtable-Viewer/commit/9b3c88d135c0597b01aa891798f1f42c7dcc0b21#diff-30dd23cdaf47e9c3c1b9d01b50f78f4910d7885283136909acf01f9374d521c4L24

I'll add it back, but it won't have any other languages.

**Comment by R3voA3** [comment]
I'll add it back and also add the German string.
